



##                                                  word Associations game

word_associations = {
    "cat": ["meow", "pet", "furry", "whiskers"],
    "dog": ["bark", "loyal", "fetch", "tail"],
    "banana": ["yellow", "fruit", "peel", "monkey"],
    "computer": ["technology", "screen", "keyboard", "internet"],
    "coffee": ["caffeine", "aroma", "morning", "beans"],
    "book": ["read", "pages", "story", "library"],
    "rain": ["wet", "umbrella", "pitter-patter", "storm"],
    "guitar": ["music", "strings", "strum", "instrument"],
    "sun": ["shine", "bright", "warmth", "day"],
    "cake": ["sweet", "dessert", "celebration", "bake"],
    "car": ["drive", "engine", "road", "speed"],
    "tree": ["leaves", "branches", "nature", "shade"],
    "ocean": ["waves", "blue", "beach", "sea"],
    "fire": ["heat", "flames", "burn", "campfire"],
    "friend": ["company", "trust", "laughter", "support"],
    "rainbow": ["colors", "sky", "rain", "pot of gold"],
    "pizza": ["cheese", "toppings", "slice", "delivery"],
    "flower": ["blossom", "fragrance", "garden", "petal"],
    "moon": ["night", "glow", "lunar", "stars"],
    "music": ["melody", "rhythm", "harmony", "song"],
    "beach": ["sand", "waves", "seashells", "sunscreen"],
    "mountain": ["summit", "climb", "heights", "scenery"],
    "painting": ["art", "canvas", "colors", "brush"],
    "bicycle": ["ride", "pedal", "wheels", "exercise"],
    "chocolate": ["sweet", "indulgence", "dessert", "cocoa"],
    "phone": ["call", "text", "ringtone", "smartphone"],
    "school": ["class", "teacher", "students", "learning"],
    "movie": ["film", "cinema", "actors", "plot"],
    "beauty": ["attractive", "appearance", "graceful", "aesthetic"],
    "dream": ["sleep", "imagination", "aspiration", "fantasy"],
    "game": ["play", "fun", "competition", "win"],
    "travel": ["explore", "adventure", "journey", "destination"],
    "food": ["eat", "taste", "cook", "delicious"],
    "love": ["affection", "romance", "heart", "care"],
    "art": ["creative", "expression", "beauty", "inspiration"],
    "health": ["wellness", "fitness", "lifestyle", "nutrition"],
    "nature": ["environment", "outdoors", "scenery", "wildlife"],
    "sleep": ["rest", "night", "bed", "dreams"],
    "river": ["flow", "water", "stream", "bank"],
    "candle": ["light", "flame", "wax", "burning"],
    "mirror": ["reflection", "image", "glass", "vanity"],
    "camera": ["photograph", "lens", "capture", "shutter"],
    "dance": ["music", "movement", "rhythm", "choreography"],
    "cloud": ["sky", "weather", "white", "fluffy"],
    "pen": ["write", "ink", "paper", "ballpoint"],
    "umbrella": ["rain", "protection", "weather", "foldable"],
    "clock": ["time", "ticking", "hour", "minute"],
    "shoes": ["footwear", "walking", "comfort", "laces"],
    "wallet": ["money", "cash", "cards", "pocket"],
    "key": ["lock", "door", "metal", "unlock"],
    "musician": ["instrument", "performance", "band", "talent"],
    "cup": ["drink", "mug", "handle", "tea"],
    "bird": ["feather", "fly", "wing", "nest"],
    "window": ["glass", "view", "frame", "pane"],
    "bike": ["cycle", "pedal", "ride", "bicycle"],
    "star": ["celestial", "sky", "shine", "night"],
    "camera": ["photograph", "lens", "capture", "shutter"],
    "chef": ["cook", "kitchen", "restaurant", "cuisine"],
    "garden": ["flowers", "plants", "green", "nature"],
    "cloud": ["sky", "weather", "white", "fluffy"],
    "moon": ["night", "lunar", "orbit", "crater"],
    "coffee": ["caffeine", "drink", "mug", "aroma"],
    "computer": ["technology", "screen", "keyboard", "mouse"],
    "internet": ["web", "online", "connect", "surf"],
    "sky": ["blue", "clouds", "day", "horizon"],
    "river": ["water", "flow", "stream", "bank"],
    "paint": ["brush", "art", "colors", "canvas"],
    "book": ["read", "pages", "story", "novel"],
    "phone": ["call", "talk", "smartphone", "mobile"],
    "door": ["open", "close", "entry", "exit"],
    "light": ["bright", "lamp", "illuminate", "shine"],
    "earth": ["planet", "world", "globe", "environment"],
    
    "chair": ["sit", "furniture", "seat", "comfort"],
    "mirror": ["reflection", "image", "glass", "vanity"],
    "dance": ["music", "movement", "rhythm", "choreography"],
    "cup": ["drink", "mug", "handle", "tea"],
    "bird": ["feather", "fly", "wing", "nest"],
    "window": ["glass", "view", "frame", "pane"],
    "bike": ["cycle", "pedal", "ride", "bicycle"],
    "star": ["celestial", "shine", "night", "sky"],
    "chef": ["cook", "kitchen", "restaurant", "cuisine"],
    "garden": ["flowers", "plants", "green", "nature"],
    "mountain": ["summit", "climb", "heights", "scenery"],
    "bicycle": ["ride", "pedal", "wheels", "exercise"],
    "chocolate": ["sweet", "indulgence", "dessert", "cocoa"],
    "school": ["class", "teacher", "students", "learning"],
    "movie": ["film", "cinema", "actors", "plot"],
    "beauty": ["attractive", "appearance", "graceful", "aesthetic"],
    "dream": ["sleep", "imagination", "aspiration", "fantasy"],
    "game": ["play", "fun", "competition", "win"],
    "travel": ["explore", "adventure", "journey", "destination"],
    "food": ["eat", "taste", "cook", "delicious"],
    "love": ["affection", "romance", "heart", "care"],
    "art": ["creative", "expression", "beauty", "inspiration"],
    "health": ["wellness", "fitness", "lifestyle", "nutrition"],
    "nature": ["environment", "outdoors", "scenery", "wildlife"],
    "sleep": ["rest", "night", "bed", "dreams"],
    "candle": ["light", "flame", "wax", "burning"],
    "pen": ["write", "ink", "paper", "ballpoint"],
    "umbrella": ["rain", "protection", "weather", "foldable"],
    "clock": ["time", "ticking", "hour", "minute"],
    "shoes": ["footwear", "walking", "comfort", "laces"],
    "wallet": ["money", "cash", "cards", "pocket"],
    "key": ["lock", "door", "metal", "unlock"],
    "musician": ["instrument", "performance", "band", "talent"],
    
    "cup": ["drink", "mug", "handle", "tea"],
    "bird": ["feather", "fly", "wing", "nest"],
    "window": ["glass", "view", "frame", "pane"],
    "bike": ["cycle", "pedal", "ride", "bicycle"],
    "star": ["celestial", "shine", "night", "sky"],
    "chef": ["cook", "kitchen", "restaurant", "cuisine"],
    "garden": ["flowers", "plants", "green", "nature"],
    "mountain": ["summit", "climb", "heights", "scenery"],
    "bicycle": ["ride", "pedal", "wheels", "exercise"],
    "chocolate": ["sweet", "indulgence", "dessert", "cocoa"],
    "school": ["class", "teacher", "students", "learning"],
    "movie": ["film", "cinema", "actors", "plot"],
    "beauty": ["attractive", "appearance", "graceful", "aesthetic"],
    "dream": ["sleep", "imagination", "aspiration", "fantasy"],
    "game": ["play", "fun", "competition", "win"],
    "travel": ["explore", "adventure", "journey", "destination"],
    "food": ["eat", "taste", "cook", "delicious"],
    "love": ["affection", "romance", "heart", "care"],
    "art": ["creative", "expression", "beauty", "inspiration"],
    "health": ["wellness", "fitness", "lifestyle", "nutrition"],
    "nature": ["environment", "outdoors", "scenery", "wildlife"],
    "sleep": ["rest", "night", "bed", "dreams"],
    "candle": ["light", "flame", "wax", "burning"],
    "pen": ["write", "ink", "paper", "ballpoint"],
    "umbrella": ["rain", "protection", "weather", "foldable"],
    "clock": ["time", "ticking", "hour", "minute"],
    "shoes": ["footwear", "walking", "comfort", "laces"],
    "wallet": ["money", "cash", "cards", "pocket"],
    "key": ["lock", "door", "metal", "unlock"],
    "musician": ["instrument", "performance", "band", "talent"],
    
    "camera": ["photograph", "lens", "capture", "shutter"],
    "cloud": ["sky", "weather", "white", "fluffy"],
    "moon": ["night", "lunar", "orbit", "crater"],
    "coffee": ["caffeine", "drink", "mug", "aroma"],
    "computer": ["technology", "screen", "keyboard", "mouse"],
    "internet": ["web", "online", "connect", "surf"],
    "sky": ["blue", "clouds", "day", "horizon"],
    "river": ["water", "flow", "stream", "bank"],
    "paint": ["brush", "art", "colors", "canvas"],
    "book": ["read", "pages", "story", "novel"],
    "phone": ["call", "talk", "smartphone", "mobile"],
    "door": ["open", "close", "entry", "exit"],
    "light": ["bright", "lamp", "illuminate", "shine"],
    "earth": ["planet", "world", "globe", "environment"]
}




##                                                      Guessing animal name using sound

sound_files = {
    "bee" : "honey",
    "cow" : 'cow',
    "dog" : "dog",
    'dragon' : 'dragon',
    "hen" : 'hen',
    "monkey" : 'monkey',
    "monster" : 'monster',
    'pig' : 'pig'
    # Add more sound files and descriptions as needed
}



 
##                                                    word_scramble_game game 

word_list = ["python", "programming", "computer", "algorithm", "keyboard", "developer", "internet", "database", "software", "application",
             "hardware", "network", "binary", "memory", "processor", "code", "interface", "server", "cybersecurity", "monitor"]



#                               memory_game

# List of colors for the game
color_list = ["red", "blue", "green", "yellow", "orange", "purple", "pink", "brown", "gray"]





## Eductional Context

educational_content = {
    'blockchain': ['Blockchain Basics', 'Smart Contracts', 'Decentralized Applications'],
    'quantum computing': ['Quantum Computing Principles', 'Quantum Algorithms', 'Quantum Machine Learning'],
    'augmented reality': ['Introduction to Augmented Reality', 'ARKit for iOS Development', 'ARCore for Android Development'],
    'virtual reality': ['Virtual Reality Fundamentals', 'Unity VR Development', 'Unreal Engine VR Development'],
    'bioinformatics': ['Introduction to Bioinformatics', 'Biological Data Analysis', 'Genomic Data Visualization'],
    'natural language processing': ['NLP Basics', 'Text Processing with NLTK', 'Sentiment Analysis'],
    'computer vision': ['Computer Vision Fundamentals', 'OpenCV Basics', 'Object Detection and Tracking'],
    'robotics': ['Robotics Fundamentals', 'ROS (Robot Operating System)', 'Introduction to Robotics Programming'],
    'IoT': ['Internet of Things Basics', 'IoT Security', 'IoT Protocols and Communication'],
    'big data': ['Big Data Fundamentals', 'Hadoop and MapReduce', 'Apache Spark Basics'],
    'cloud computing': ['Introduction to Cloud Computing', 'AWS Cloud Practitioner Essentials', 'Azure Fundamentals'],
    'game development': ['Unity Game Development', '2D Game Development with Pygame', 'Introduction to Unreal Engine'],
    'mobile app development': ['iOS App Development with Swift', 'Android App Development with Kotlin', 'Flutter for Mobile Development'],
    'cybersecurity': ['Cybersecurity Fundamentals', 'Ethical Hacking', 'Network Security'],
    'data science': ['Data Science Essentials', 'Data Visualization with Matplotlib', 'Introduction to Pandas'],
    'web development': ['Full Stack Web Development Bootcamp', 'HTML & CSS Basics', 'JavaScript for Beginners'],
    'python': ['Python Crash Course', 'Learn Python in 30 Days', 'Python Basics Tutorial'],
    'artificial intelligence': ['AI Basics', 'Neural Networks and Deep Learning', 'Natural Language Processing with Python'],
    'machine learning': ['Machine Learning Fundamentals', 'Supervised Learning Techniques', 'Unsupervised Learning Algorithms'],
    'deep learning': ['Deep Learning Fundamentals', 'Convolutional Neural Networks', 'Recurrent Neural Networks'],
    'computer graphics': ['Computer Graphics Principles', 'OpenGL Programming', 'Graphics Rendering Techniques'],
    'networking': ['Networking Fundamentals', 'TCP/IP Protocols', 'Network Routing and Switching'],
    'software engineering': ['Software Development Lifecycle', 'Agile Methodology', 'Design Patterns in Software Engineering'],
    'operating systems': ['Operating System Concepts', 'Linux System Administration', 'Windows Kernel Programming'],
    'database management': ['Database Systems Concepts', 'SQL Fundamentals', 'NoSQL Databases'],
    'digital marketing': ['Digital Marketing Essentials', 'Social Media Marketing Strategies', 'Search Engine Optimization (SEO)'],
    'financial literacy': ['Personal Finance Basics', 'Investment Strategies', 'Financial Planning'],
    'business management': ['Business Fundamentals', 'Strategic Management', 'Leadership Skills Development'],
    'entrepreneurship': ['Entrepreneurship Principles', 'Startup Fundamentals', 'Business Model Innovation'],
    'public speaking': ['Effective Public Speaking', 'Presentation Skills Development', 'Storytelling Techniques'],
    'creative writing': ['Creative Writing Fundamentals', 'Fiction Writing Workshop', 'Poetry Writing Techniques'],
    'art history': ['Art History Survey', 'Renaissance Art', 'Modern Art Movements'],
    'music theory': ['Music Theory Basics', 'Composition Techniques', 'Music Production Fundamentals'],
    'film studies': ['Film History', 'Cinematic Techniques', 'Screenwriting Fundamentals'],
    'photography': ['Photography Basics', 'Digital Photography Editing', 'Portrait Photography Techniques'],
    'astronomy': ['Astronomy Fundamentals', 'Observational Astronomy', 'Cosmology'],
    'psychology': ['Psychology Fundamentals', 'Cognitive Psychology', 'Abnormal Psychology'],
    'sociology': ['Sociology Principles', 'Social Structures and Institutions', 'Cultural Anthropology'],
    'philosophy': ['Philosophy Basics', 'Ethics and Moral Philosophy', 'Political Philosophy'],
    'history': ['World History Survey', 'American History', 'European History'],
    'geography': ['Geography Fundamentals', 'Human Geography', 'Physical Geography'],
    'biology': ['Biology Basics', 'Cell Biology', 'Evolutionary Biology'],
    'chemistry': ['Chemistry Fundamentals', 'Organic Chemistry', 'Physical Chemistry'],
    'physics': ['Physics Essentials', 'Classical Mechanics', 'Quantum Physics'],
    'mathematics': ['Mathematics Fundamentals', 'Calculus', 'Linear Algebra'],
    'literature': ['Literature Survey', 'English Literature', 'World Literature'],
    'languages': ['Language Learning Basics', 'Spanish Language', 'French Language'],
    'coding bootcamps': ['Coding Bootcamp Prep', 'Full Stack Web Development Bootcamp', 'Data Science Bootcamp'],
    'test preparation': ['SAT Preparation', 'ACT Preparation', 'GRE Exam Study'],
    'health and wellness': ['Healthy Living Tips', 'Fitness Training', 'Nutrition Essentials'],
    'cooking and baking': ['Cooking Basics', 'Baking Techniques', 'International Cuisine'],
    'gardening': ['Gardening Tips', 'Vegetable Gardening', 'Landscaping Ideas'],
    'DIY crafts': ['Crafting Ideas', 'DIY Home Decor', 'Upcycling Projects'],
    'travel and adventure': ['Travel Planning Tips', 'Adventure Travel Destinations', 'Budget Travel Hacks'],
    'mindfulness and meditation': ['Mindfulness Exercises', 'Meditation Techniques', 'Stress Reduction Strategies'],
    'yoga and fitness': ['Yoga Basics', 'Strength Training Workouts', 'Cardiovascular Exercise'],
    'parenting and family': ['Parenting Advice', 'Child Development Milestones', 'Family Bonding Activities'],
    'pet care': ['Pet Care Basics', 'Dog Training Tips', 'Cat Health and Nutrition'],
    'cobol': ['COBOL Basics', 'Mainframe Programming with COBOL', 'COBOL Data Structures'],
    'fortran': ['FORTRAN Programming Essentials', 'Scientific Computing with FORTRAN', 'FORTRAN Optimization Techniques'],
    'pascal': ['Pascal Programming Fundamentals', 'Object-Oriented Pascal', 'Pascal Data Structures'],
    'ada': ['Ada Programming Basics', 'Ada Software Development', 'Ada Concurrency and Real-Time Programming'],
    'lisp': ['Lisp Programming Essentials', 'Common Lisp Development', 'Scheme Programming Language'],
    'prolog': ['Prolog Basics', 'Logic Programming with Prolog', 'Expert Systems Development'],
    'forth': ['Forth Programming Fundamentals', 'Embedded Forth Programming', 'Forth Compiler Design'],
    'apl': ['APL Programming Basics', 'Array Programming with APL', 'APL Language Features'],
    'julia': ['Julia Programming Essentials', 'Scientific Computing with Julia', 'Parallel Programming in Julia'],
    'erlang': ['Erlang Basics', 'Concurrent Programming with Erlang', 'Distributed Systems with Erlang'],
    'verilog': ['Verilog HDL Fundamentals', 'Digital Design with Verilog', 'FPGA Programming with Verilog'],
    'vhdl': ['VHDL Basics', 'VHDL Synthesis Techniques', 'Hardware Description and Verification in VHDL'],
    'cobol': ['COBOL Basics', 'Mainframe Programming with COBOL', 'COBOL Data Structures'],
    'fortran': ['FORTRAN Programming Essentials', 'Scientific Computing with FORTRAN', 'FORTRAN Optimization Techniques'],
    'pascal': ['Pascal Programming Fundamentals', 'Object-Oriented Pascal', 'Pascal Data Structures'],
    'ada': ['Ada Programming Basics', 'Ada Software Development', 'Ada Concurrency and Real-Time Programming'],
    'lisp': ['Lisp Programming Essentials', 'Common Lisp Development', 'Scheme Programming Language'],
    'prolog': ['Prolog Basics', 'Logic Programming with Prolog', 'Expert Systems Development'],
    'forth': ['Forth Programming Fundamentals', 'Embedded Forth Programming', 'Forth Compiler Design'],
    'apl': ['APL Programming Basics', 'Array Programming with APL', 'APL Language Features'],
    'julia': ['Julia Programming Essentials', 'Scientific Computing with Julia', 'Parallel Programming in Julia'],
    'erlang': ['Erlang Basics', 'Concurrent Programming with Erlang', 'Distributed Systems with Erlang'],
    'verilog': ['Verilog HDL Fundamentals', 'Digital Design with Verilog', 'FPGA Programming with Verilog'],
    'vhdl': ['VHDL Basics', 'VHDL Synthesis Techniques', 'Hardware Description and Verification in VHDL'],
    'ada': ['Ada Programming Basics', 'Ada Software Development', 'Ada Concurrency and Real-Time Programming'],
    'cobol': ['COBOL Basics', 'Mainframe Programming with COBOL', 'COBOL Data Structures'],
    'forth': ['Forth Programming Fundamentals', 'Embedded Forth Programming', 'Forth Compiler Design'],
    'verilog': ['Verilog HDL Fundamentals', 'Digital Design with Verilog', 'FPGA Programming with Verilog'],
    'pascal': ['Pascal Programming Fundamentals', 'Object-Oriented Pascal', 'Pascal Data Structures'],
    'lisp': ['Lisp Programming Essentials', 'Common Lisp Development', 'Scheme Programming Language'],
    'apl': ['APL Programming Basics', 'Array Programming with APL', 'APL Language Features'],
    'prolog': ['Prolog Basics', 'Logic Programming with Prolog', 'Expert Systems Development'],
    'vhdl': ['VHDL Basics', 'VHDL Synthesis Techniques', 'Hardware Description and Verification in VHDL'],
    'lua': ['Lua Programming Basics', 'Game Development with Lua', 'Scripting in Lua'],
    'dart': ['Dart Programming Fundamentals', 'Flutter Development', 'Server-Side Dart'],
    'scala': ['Scala Programming Basics', 'Functional Programming with Scala', 'Scala for Big Data'],
    'haskell': ['Haskell Basics', 'Functional Programming Principles', 'Web Development with Haskell'],
    'groovy': ['Groovy Programming Essentials', 'Scripting with Groovy', 'Gradle Build Automation'],
    'elixir': ['Elixir Programming Fundamentals', 'Concurrency in Elixir', 'Phoenix Framework'],
    'clojure': ['Clojure Programming Basics', 'Functional Programming with Clojure', 'ClojureScript'],
    'typescript': ['TypeScript Fundamentals', 'Advanced TypeScript Concepts', 'Angular Development'],
    'php': ['PHP Programming Essentials', 'Building Dynamic Websites with PHP', 'Laravel Framework'],
    'perl': ['Perl Programming Basics', 'Text Processing with Perl', 'Web Development with Perl'],
    'bash': ['Bash Scripting Fundamentals', 'Linux Shell Scripting', 'Automating System Tasks'],
    'html': ['HTML Basics', 'HTML5 Features and Elements', 'Web Development with HTML'],
    'css': ['CSS Fundamentals', 'Responsive Web Design', 'CSS Preprocessors'],
    'sql': ['SQL Basics', 'Database Management with SQL', 'Advanced SQL Techniques'],
    'assembly': ['Assembly Language Basics', 'x86 Assembly Programming', 'Microcontroller Programming'],
    'r': ['R Programming Essentials', 'Data Analysis with R', 'Data Visualization in R'],
    'matlab': ['MATLAB Fundamentals', 'Numerical Computing with MATLAB', 'Image Processing with MATLAB'],
    'lua': ['Lua Programming Basics', 'Game Development with Lua', 'Scripting in Lua'],
    'dart': ['Dart Programming Fundamentals', 'Flutter Development', 'Server-Side Dart'],
    'scala': ['Scala Programming Basics', 'Functional Programming with Scala', 'Scala for Big Data'],
    'haskell': ['Haskell Basics', 'Functional Programming Principles', 'Web Development with Haskell'],
    'groovy': ['Groovy Programming Essentials', 'Scripting with Groovy', 'Gradle Build Automation'],
    'elixir': ['Elixir Programming Fundamentals', 'Concurrency in Elixir', 'Phoenix Framework'],
    'clojure': ['Clojure Programming Basics', 'Functional Programming with Clojure', 'ClojureScript'],
    'c++': ['C++ Programming Fundamentals', 'Object-Oriented Programming with C++', 'STL and Standard Library in C++'],
    'c#': ['C# Programming Basics', '.NET Development with C#', 'Game Development with Unity'],
    'java': ['Java Programming Fundamentals', 'Advanced Java Concepts', 'Java Web Development'],
    'javascript': ['JavaScript Basics', 'Frontend Development with JavaScript', 'Node.js and Express.js'],
    'typescript': ['TypeScript Fundamentals', 'Angular Development with TypeScript', 'React Development with TypeScript'],
    'swift': ['Swift Programming Basics', 'iOS App Development with Swift', 'SwiftUI Development'],
    'kotlin': ['Kotlin Programming Fundamentals', 'Android App Development with Kotlin', 'Kotlin Coroutines'],
    'rust': ['Rust Programming Basics', 'Systems Programming with Rust', 'Web Development with Rocket'],
    'go': ['Go Programming Fundamentals', 'Concurrency in Go', 'Web Development with Go'],
    'python': ['Python Programming Basics', 'Data Science with Python', 'Web Development with Django'],
    'ruby': ['Ruby Programming Fundamentals', 'Ruby on Rails Web Development', 'Scripting with Ruby'],
    'php': ['PHP Programming Basics', 'Web Development with PHP', 'Laravel Framework'],
    'perl': ['Perl Programming Fundamentals', 'Text Processing with Perl', 'Web Development with Catalyst'],
    'bash': ['Bash Scripting Basics', 'Linux System Administration with Bash', 'Bash Shell Scripting'],
    'html': ['HTML Basics', 'HTML5 Features and Elements', 'Web Development with HTML and CSS'],
    'css': ['CSS Fundamentals', 'Advanced CSS Techniques', 'CSS Grid and Flexbox Layouts'],
    'sql': ['SQL Basics', 'Database Design and Implementation', 'Advanced SQL Queries'],
    'assembly': ['Assembly Language Fundamentals', 'x86 Assembly Programming', 'Microcontroller Assembly']
}






## Cities time
cities = {
    'Usa': 'America/New_York',
    'United kingdom': 'Europe/London',
    'Japan': 'Asia/Tokyo',
    'Australia': 'Australia/Sydney',
    'France': 'Europe/Paris',
    'Uae': 'Asia/Dubai',
    'Russia': 'Europe/Moscow',
    'China': 'Asia/Shanghai',
    'Singapore': 'Asia/Singapore',
    'Canada': 'America/Toronto',
    'Germany': 'Europe/Berlin',
    'South korea': 'Asia/Seoul',
    'Brazil': 'America/Sao_Paulo',
    'India': 'Asia/Kolkata',
    'Italy': 'Europe/Rome',
    'Spain': 'Europe/Madrid',
    'Mexico': 'America/Mexico_City',
    'Netherlands': 'Europe/Amsterdam',
    'Switzerland': 'Europe/Zurich',
    'Sweden': 'Europe/Stockholm',
    'Turkey': 'Europe/Istanbul',
    'Argentina': 'America/Argentina/Buenos_Aires',
    'South africa': 'Africa/Johannesburg',
    'Egypt': 'Africa/Cairo',
    'Saudi arabia': 'Asia/Riyadh',
    'Thailand': 'Asia/Bangkok',
    'Vietnam': 'Asia/Ho_Chi_Minh',
    'Malaysia': 'Asia/Kuala_Lumpur',
    'Indonesia': 'Asia/Jakarta',
    'Philippines': 'Asia/Manila',
    'Pakistan': 'Asia/Karachi',
    'Bangladesh': 'Asia/Dhaka',
    'Sri lanka': 'Asia/Colombo',
    'Nigeria': 'Africa/Lagos',
    'Kenya': 'Africa/Nairobi',
    'Ghana': 'Africa/Accra',
    'Peru': 'America/Lima',
    'Chile': 'America/Santiago',
    'Colombia': 'America/Bogota',
    'Venezuela': 'America/Caracas',
    'Cuba': 'America/Havana',
    'Puerto rico': 'America/Puerto_Rico',
    'Jamaica': 'America/Jamaica'
}